version: '3.5'
# docker build -t rinha-api . && docker compose up
services:
  api1: &app
    image: rinha-api
    hostname: api1
    restart: always
    depends_on:
      - db
    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: Rinha
      DB_USER: rinha
      DB_PASSWORD: rinhasenha
      DB_POOL: 35
    expose:
      - "3000"
    deploy:
      resources:
        limits:
          cpus: '0.30'
          memory: '0.65GB'
    networks:
      - rinhanetwork

  api2:
    <<: *app
    hostname: api2 

  nginx: # Load Balancer
    image: nginx:stable
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.40GB'
    networks:
      - rinhanetwork
  db:
    image: postgres:16
    hostname: db
    restart: always
    command: postgres -c 'max_connections=450'
    environment:
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinhasenha
      POSTGRES_DB: Rinha
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: '1.30GB'
    networks:
      - rinhanetwork

networks:
  rinhanetwork:
    driver: bridge
